#!/bin/bash

# THIS BUNRU IS THE TESTS BUNRU, CONSIDER USING THE OTHER BUNRU EXECUTABLE THAT IS LOCATED IN THE "BIN/" FOLDER.
# NASM BUILD AND RUNNER (BUNRU) BY DUSTGUSS
# https://github.com/DustoGuss/bunru

files=("$@") 
flag="${files[-1]}"
unset 'files[-1]'

GREEN="\033[32m"
BLUE="\033[34m"
RED="\033[31m"
BOLD="\033[1m"
RESET="\033[0m"

build() {
    for file in "${files[@]}"; do
        echo -e "${BOLD}$file:${RESET}"
        echo -e "${BOLD}${BLUE}[Compiling $file...]${RESET}"
        if [ -f "$file.asm" ]; then
            nasm -f elf64 -o "$file.o" "$file.asm"
        else
            nasm -f elf64 -o "$file.o" "$file.s"
        fi
        echo -e "${BOLD}${GREEN}[Compiled $file!]${RESET}"
        echo "----------"
        echo -e "${BOLD}${BLUE}[Linking $file...]${RESET}"
        ld "$file.o" -o "$file"
        echo -e "${BOLD}${GREEN}[Linked $file!]${RESET}"
        local exit_code=$? 

        if [ $exit_code -eq 0 ]; then
            echo -e "${BOLD}${GREEN}Build of $file ended without errors! :D${RESET}"
        else
            echo -e "${BOLD}${RED}Build of $file ended with errors... D:${RESET}"
        fi
        echo "---------"
    done
}

run() {
    for file in "${files[@]}"; do
        echo -e "${BOLD}$file:${RESET}"
        echo -e "${BOLD}${BLUE}[Running $file...]${RESET}"
        ./"$file"
        local exit_code=$? 

        if [ $exit_code -eq 0 ]; then
            echo -e "${BOLD}${GREEN}Program $file ended without errors! :D${RESET}"
        else
            echo -e "${BOLD}${RED}Program $file ended with errors... D:${RESET}"
        fi
        echo "------------"
    done
}

debug() {
    for file in "${files[@]}"; do
        echo -e "${BOLD}${BLUE}[Debugging $file...]${RESET}"
        
        if [ -f "$file.asm" ]; then
            nasm -f elf64 -o "tempdebug$file.o" "$file.asm"
        else
            nasm -f elf64 -o "tempdebug$file.o" "$file.s"
        fi
        ld "tempdebug$file.o" -o "tempdebug$file"
        local builderror=$?

        if [ $builderror -ne 0 ]; then
            echo -e "${BOLD}${RED}Debug of $file ended with errors during build... D:${RESET}"
            return $builderror
        fi

        ./"tempdebug$file"
        local runerror=$?

        if [ $runerror -eq 0 ]; then
            echo -e "${BOLD}${GREEN}Debug of $file ended without errors! :D${RESET}"
        else
            echo -e "${BOLD}${RED}Debug of $file ended with errors during execution... D:${RESET}"
        fi
        rm -f "tempdebug$file.o" "tempdebug$file"
    done
}

if [[ "$flag" == "-b" ]]; then
    build
elif [[ "$flag" == "-d" ]]; then
    debug
elif [[ "$flag" == "-r" ]]; then
    build
    run
else
    echo -e "${BOLD}${RED}Invalid flag! Use -b to build, -d to debug or -r to build and run.${RESET}"
fi
